CREATE TABLE "AFIANDWH"."USERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"BIRTHDATE" DATE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID"));

CREATE SEQUENCE USERS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER USERS_BIR 
BEFORE INSERT ON USERS 
FOR EACH ROW

BEGIN
  SELECT USERS_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;   